from .chinese_word_swap_wordnet import ChineseWordSwapWordNet
from .Argot_transformation import ChineseArgotWordSwap, ChineseShuffleCharacterSwap, ChineseSplittingCharacterSwap, ChineseHomophoneCharacterSwap, ChineseSimilarPinyinCharacterSwap, ChineseSynonymWordSwap, ChineseGlyphCharacterSwap
from .chinese_word_swap_hownet import ChineseWordSwapHowNet
from .chinese_word_swap_soundshapecode import ChineseSSCCharacterSwap, mix_ssc
from .chinese_word_swap_masked import ChineseWordSwapMaskedLM
from .expanding_scope import ChineseExpandingScopeWordSwap